git clone https://github.com/cisco-gve/cmx
git clone https://github.com/cisco-gve/esa
git clone https://github.com/cisco-gve/fmc
git clone https://github.com/cisco-gve/spark-tropo
git clone https://github.com/cisco-gve/prime-infrastructure
git clone https://github.com/cisco-gve/cucm-tp
git clone https://github.com/cisco-gve/iox
git clone https://github.com/cisco-gve/epnm
git clone https://github.com/cisco-gve/cam
git clone https://github.com/cisco-gve/umbrella
git clone https://github.com/cisco-gve/nso
git clone https://github.com/cisco-gve/amp
git clone https://github.com/cisco-gve/ise
git clone https://github.com/cisco-gve/nx-os
git clone https://github.com/cisco-gve/wae
git clone https://github.com/cisco-gve/apic-dc
